config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }

    # @return [String]
    def wow_title
        self.title == 'wow' ? "wow" : 0
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# app/controllers/articles_controller.rb
# This is the controller for the articles model
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
    @article.wow_title
  end

  def create
    #    render plain: params[:article].inspect
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        flash[:notice] = 'Article was successfully created'
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
    # Try catch
    @article = Article.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = 'Article not found'
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
    render
  end

  def update
    @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        flash[:notice] = 'Article was successfully updated'
        format.html { redirect_to @article }
      else
        flash[:notice] = 'Article was not updated'
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      @article.destroy
      flash[:notice] = 'Article was deleted'
      format.html { redirect_to articles_path }
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h2>Edit Article</h2>

<%= form_for @article do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>

app/views/articles/index.html.erb
<%= link_to "Create Article", new_article_path %>

<h1>Listing all articles</h1>
<table>
 <tr>
  <th>Title</th>
  <th>Description</th>
  <th> Open </th>
  <th> Edit </th>
 </tr>
 <% @articles.each do |article| %>
 <tr>
  <td><%= article.title %></td>
  <td><%= article.description %></td>
    <td><%= link_to "Open", article_path(article) %></td>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" } %></td>
 </tr>
 <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>

<%= form_for @article do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>
 Title: <%= @article.title %>
</p>
<p>
 Description: <%= @article.description %>
</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>

  <% flash.each do |name, msg| %>
    <ul>
     <li><%= msg %></li>
    </ul>
  <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About Blog</h1>
<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>
<%= link_to 'About', about_path %>